// import 'package:flutter/material.dart';
//
// class AppConstants {
//   ///Product RSS display string
//   static final Map<String, String> rssProducts = {
//     '1': 'Unleaded Petrol',
//     '2': 'Premium Unleaded',
//     '4': 'Diesel',
//     '5': 'LPG',
//     '6': '98 RON',
//     '10': 'E85',
//     '11': 'Brand Diesel'
//   };
//
//   ///Product RSS short string
//   static final Map<String, String> rssProductsShort = {
//     '1': 'ULP',
//     '2': 'PULP',
//     '4': 'D',
//     '5': 'LPG',
//     '6': '98 RON',
//     '10': 'E85',
//     '11': 'BD'
//   };
//
//   ///Product RSS color
//   static final Map<String, Color> rssProductsColors = {
//     '1': Colors.indigoAccent,
//     '2': Colors.purple,
//     '4': Colors.teal,
//     '5': Colors.tealAccent,
//     '6': Colors.yellow,
//     '10': Colors.grey,
//     '11': Colors.brown
//   };
//
//   ///Region RSS display string
//   static final Map<String, String> rssRegions = {
//     '25': 'Metro : North of River',
//     '26': 'Metro : South of River',
//     '27': 'Metro : East/Hills',
//     '15': 'Albany',
//     '28': 'Augusta / Margaret River',
//     '30': 'Bridgetown / Greenbushes',
//     '1': 'Boulder',
//     '2': 'Broome',
//     '16': 'Bunbury',
//     '3': 'Busselton (Townsite)',
//     '29': 'Busselton (Shire)',
//     '19': 'Capel',
//     '4': 'Carnarvon',
//     '33': 'Cataby',
//     '5': 'Collie',
//     '34': 'Coolgardie',
//     '35': 'Cunderdin',
//     '31': 'Donnybrook / Balingup',
//     '36': 'Dalwallinu',
//     '6': 'Dampier',
//     '20': 'Dardanup',
//     '37': 'Denmark',
//     '38': 'Derby',
//     '39': 'Dongara',
//     '7': 'Esperance',
//     '40': 'Exmouth',
//     '41': 'Fitzroy Crossing',
//     '17': 'Geraldton',
//     '21': 'Greenough',
//     '22': 'Harvey',
//     '42': 'Jurien',
//     '8': 'Kalgoorlie',
//     '43': 'Kambalda',
//     '9': 'Karratha',
//     '44': 'Kellerberrin',
//     '45': 'Kojonup',
//     '10': 'Kununurra',
//     '18': 'Mandurah',
//     '32': 'Manjimup',
//     '58': 'Meckering',
//     '46': 'Meekatharra',
//     '47': 'Moora',
//     '48': 'Mt Barker',
//     '61': 'Munglinup',
//     '23': 'Murray',
//     '11': 'Narrogin',
//     '49': 'Newman',
//     '50': 'Norseman',
//     '60': 'North Bannister',
//     '12': 'Northam',
//     '62': 'Northam (Shire)',
//     '13': 'Port Hedland',
//     '51': 'Ravensthorpe',
//     '57': 'Regans Ford',
//     '14': 'South Hedland',
//     '53': 'Tammin',
//     '24': 'Waroona',
//     '54': 'Williams',
//     '55': 'Wubin',
//     '59': 'Wundowie',
//     '56': 'York',
//   };
//
//   ///Brand RSS display string
//   static final Map<String, String> rssBrands = {
//     '0': 'Any Brand',
//     '29': '7-Eleven',
//     '2': 'Ampol',
//     '3': 'Better Choice',
//     '4': 'BOC',
//     '5': 'BP',
//     '6': 'Caltex',
//     '19': 'Caltex Woolworths',
//     '20': 'Coles Express',
//     '32': 'Costco',
//     '24': 'Eagle',
//     '25': 'FastFuel 24/7',
//     '7': 'Gull',
//     '15': 'Independent',
//     '8': 'Kleenheat',
//     '9': 'Kwikfuel',
//     '10': 'Liberty',
//     '30': 'Metro Petroleum',
//     '11': 'Mobil',
//     '13': 'Peak',
//     '26': 'Puma',
//     '14': 'Shell',
//     '23': 'United',
//     '27': 'Vibe',
//     '31': 'WA Fuels',
//     '16': 'Wesco',
//   };
//
//   ///Suburb display string
//   static final List<String> rssSuburbs = [
//     'ALBANY',
//     'ALEXANDER HEIGHTS',
//     'ALFRED COVE',
//     'ALKIMOS',
//     'APPLECROSS',
//     'ARMADALE',
//     'ASCOT',
//     'ASHBY',
//     'ATTADALE',
//     'AUGUSTA',
//     'AUSTRALIND',
//     'AVELEY',
//     'BAKERS HILL',
//     'BALCATTA',
//     'BALDIVIS',
//     'BALGA',
//     'BALINGUP',
//     'BALLAJURA',
//     'BANKSIA GROVE',
//     'BARRAGUP',
//     'BASKERVILLE',
//     'BASSENDEAN',
//     'BAYSWATER',
//     'BECKENHAM',
//     'BEDFORD',
//     'BEDFORDALE',
//     'BEECHBORO',
//     'BEELIAR',
//     'BELDON',
//     'BELLEVUE',
//     'BELMONT',
//     'BENTLEY',
//     'BERTRAM',
//     'BIBRA LAKE',
//     'BICTON',
//     'BINNINGUP',
//     'BOORAGOON',
//     'BOULDER',
//     'BOYANUP',
//     'BRENTWOOD',
//     'BRIDGETOWN',
//     'BROADWATER',
//     'BROOME',
//     'BRUNSWICK',
//     'BULL CREEK',
//     'BULLSBROOK',
//     'BUNBURY',
//     'BURSWOOD',
//     'BUSSELTON',
//     'BUTLER',
//     'BYFORD',
//     'CALISTA',
//     'CANNING VALE',
//     'CANNINGTON',
//     'CAPEL',
//     'CARBUNUP RIVER',
//     'CARINE',
//     'CARLISLE',
//     'CARNARVON',
//     'CATABY',
//     'CAVERSHAM',
//     'CHIDLOW',
//     'CLAREMONT',
//     'CLARKSON',
//     'CLOVERDALE',
//     'COCKBURN CENTRAL',
//     'COLLIE',
//     'COMO',
//     'COOLGARDIE',
//     'COOLUP',
//     'COWARAMUP',
//     'CUNDERDIN',
//     'CURRAMBINE',
//     'DALWALLINU',
//     'DAMPIER',
//     'DARDANUP',
//     'DAWESVILLE',
//     'DAYTON',
//     'DENMARK',
//     'DERBY',
//     'DIANELLA',
//     'DONGARA',
//     'DONNYBROOK',
//     'DOUBLEVIEW',
//     'DUNCRAIG',
//     'DUNSBOROUGH',
//     'DWELLINGUP',
//     'EAST FREMANTLE',
//     'EAST PERTH',
//     'EAST ROCKINGHAM',
//     'EAST VICTORIA PARK',
//     'EATON',
//     'EDGEWATER',
//     'ELLENBROOK',
//     'EMBLETON',
//     'ERSKINE',
//     'ESPERANCE',
//     'EXMOUTH',
//     'FALCON',
//     'FITZROY CROSSING',
//     'FLOREAT',
//     'FORRESTDALE',
//     'FORRESTFIELD',
//     'FREMANTLE',
//     'GELORUP',
//     'GERALDTON',
//     'GIDGEGANNUP',
//     'GIRRAWHEEN',
//     'GLEN FORREST',
//     'GLEN IRIS',
//     'GLENDALOUGH',
//     'GLENFIELD',
//     'GOSNELLS',
//     'GRACETOWN',
//     'GREENBUSHES',
//     'GREENFIELDS',
//     'GREENOUGH',
//     'GREENWOOD',
//     'GUILDFORD',
//     'GWELUP',
//     'HALLS HEAD',
//     'HAMILTON HILL',
//     'HARRISDALE',
//     'HARVEY',
//     'HENDERSON',
//     'HENLEY BROOK',
//     'HERNE HILL',
//     'HIGH WYCOMBE',
//     'HILLARYS',
//     'HUNTINGDALE',
//     'INNALOO',
//     'JANDAKOT',
//     'JARRAHDALE',
//     'JINDALEE',
//     'JOLIMONT',
//     'JOONDALUP',
//     'JURIEN BAY',
//     'KALAMUNDA',
//     'KALGOORLIE',
//     'KAMBALDA EAST',
//     'KARAWARA',
//     'KARDINYA',
//     'KARNUP',
//     'KARRAGULLEN',
//     'KARRATHA',
//     'KARRIDALE',
//     'KARRINYUP',
//     'KELLERBERRIN',
//     'KELMSCOTT',
//     'KEWDALE',
//     'KIARA',
//     'KINGSLEY',
//     'KOJONUP',
//     'KOONDOOLA',
//     'KUNUNURRA',
//     'KWINANA BEACH',
//     'KWINANA TOWN CENTRE',
//     'LAKELANDS',
//     'LANDSDALE',
//     'LANGFORD',
//     'LEDA',
//     'LEEDERVILLE',
//     'LEEMING',
//     'LESMURDIE',
//     'LEXIA',
//     'LYNWOOD',
//     'MADDINGTON',
//     'MADELEY',
//     'MAIDA VALE',
//     'MALABINE',
//     'MALAGA',
//     'MANDURAH',
//     'MANJIMUP',
//     'MANNING',
//     'MANYPEAKS',
//     'MARGARET RIVER',
//     'MEADOW SPRINGS',
//     'MECKERING',
//     'MEEKATHARRA',
//     'MERRIWA',
//     'MIDDLE SWAN',
//     'MIDLAND',
//     'MIDVALE',
//     'MINDARIE',
//     'MIRRABOOKA',
//     'MOONYOONOOKA',
//     'MOORA',
//     'MORLEY',
//     'MOSMAN PARK',
//     'MOUNT BARKER',
//     'MT HELENA',
//     'MT LAWLEY',
//     'MT PLEASANT',
//     'MULLALOO',
//     'MULLEWA',
//     'MUNDARING',
//     'MUNDIJONG',
//     'MUNGLINUP',
//     'MUNSTER',
//     'MURDOCH',
//     'MYALUP',
//     'MYAREE',
//     'NARROGIN',
//     'NAVAL BASE',
//     'NEDLANDS',
//     'NEERABUP',
//     'NEWMAN',
//     'NOLLAMARA',
//     'NORANDA',
//     'NORSEMAN',
//     'NORTH BANNISTER',
//     'NORTH DANDALUP',
//     'NORTH FREMANTLE',
//     'NORTH PERTH',
//     'NORTH YUNDERUP',
//     'NORTHAM',
//     'NORTHBRIDGE',
//     'NORTHCLIFFE',
//     'NOWERGUP',
//     'O\'CONNOR',
//     'OCEAN REEF',
//     'OSBORNE PARK',
//     'PADBURY',
//     'PALMYRA',
//     'PEARSALL',
//     'PEMBERTON',
//     'PERTH',
//     'PERTH AIRPORT',
//     'PIARA WATERS',
//     'PICTON',
//     'PICTON EAST',
//     'PINJARRA',
//     'PORT HEDLAND',
//     'PORT KENNEDY',
//     'PRESTON BEACH',
//     'QUEENS PARK',
//     'QUINNS ROCKS',
//     'RAVENSTHORPE',
//     'RAVENSWOOD',
//     'REDCLIFFE',
//     'REGANS FORD',
//     'RIDGEWOOD',
//     'RIVERTON',
//     'RIVERVALE',
//     'ROCKINGHAM',
//     'ROLEYSTONE',
//     'ROSA BROOK',
//     'SAFETY BAY',
//     'SAWYERS VALLEY',
//     'SCARBOROUGH',
//     'SECRET HARBOUR',
//     'SERPENTINE',
//     'SEVILLE GROVE',
//     'SIESTA PARK',
//     'SINGLETON',
//     'SORRENTO',
//     'SOUTH FREMANTLE',
//     'SOUTH HEDLAND',
//     'SOUTH LAKE',
//     'SOUTH PERTH',
//     'SOUTH YUNDERUP',
//     'SOUTHERN RIVER',
//     'SPEARWOOD',
//     'STRATHAM',
//     'STRATTON',
//     'SUBIACO',
//     'SUCCESS',
//     'SWAN VIEW',
//     'SWANBOURNE',
//     'TAMMIN',
//     'THE LAKES',
//     'THORNLIE',
//     'TUART HILL',
//     'UPPER SWAN',
//     'VASSE',
//     'VICTORIA PARK',
//     'WAIKIKI',
//     'WALKAWAY',
//     'WALPOLE',
//     'WANGARA',
//     'WANNEROO',
//     'WARNBRO',
//     'WAROONA',
//     'WARWICK',
//     'WATERLOO',
//     'WATTLE GROVE',
//     'WEDGEFIELD',
//     'WELLSTEAD',
//     'WELSHPOOL',
//     'WEMBLEY',
//     'WEST BUSSELTON',
//     'WEST KALGOORLIE',
//     'WEST PERTH',
//     'WEST PINJARRA',
//     'WEST SWAN',
//     'WESTMINSTER',
//     'WILLETTON',
//     'WILLIAMS',
//     'WITCHCLIFFE',
//     'WOODBRIDGE',
//     'WOODVALE',
//     'WUBIN',
//     'WUNDOWIE',
//     'YANCHEP',
//     'YANGEBUP',
//     'YOKINE',
//     'YORK',
//     'YOUNGS SIDING',
//   ];
//
// }